check binaries

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -10,17 +10,23 @@ if [ $# -ne 1 ] || [ "$1" = "" ]; then
 fi
 bump="$1"
 
+# make sure we have all the required tools
+if ! which cargo cargo-set-version npm; then
+	echo "error: missing binaries" >&2
+	exit 3
+fi
+
 # make sure we are on the master branch
 branch="$(git rev-parse --abbrev-ref HEAD)"
 if [ "$branch" != master ]; then
 	echo "error: not on master branch" >&2
-	exit 3
+	exit 4
 fi
 
 # make sure the repository is clean
 if [ "$(git status --porcelain)" != "" ]; then
 	echo "error: repository is dirty" >&2
-	exit 4
+	exit 5
 fi
 
 # bump cargo version
